SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Estudiantes;
DROP TABLE IF EXISTS administrativo;
DROP TABLE IF EXISTS cliente;
DROP TABLE IF EXISTS consulta;
DROP TABLE IF EXISTS equipos;
DROP TABLE IF EXISTS estados_equipo;
DROP TABLE IF EXISTS estados_prestamo;
DROP TABLE IF EXISTS estados_solicitud;
DROP TABLE IF EXISTS estados_ticket;
DROP TABLE IF EXISTS inventario;
DROP TABLE IF EXISTS laboratorios;
DROP TABLE IF EXISTS mascota;
DROP TABLE IF EXISTS prestamos;
DROP TABLE IF EXISTS prioridades;
DROP TABLE IF EXISTS repuestos;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS tarea;
DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS tipos_equipo;
DROP TABLE IF EXISTS tipos_solicitud;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS usuarios;
DROP TABLE IF EXISTS veterinario;
DROP TABLE IF EXISTS historial_equipos;
DROP TABLE IF EXISTS solicitudes;

SET FOREIGN_KEY_CHECKS = 1;

SHOW TABLES;